# ES6 6 Compilation
#all:
#npm i
#npm i -g rollup
#node build_proto.js
#rollup index.js --output ../build/cothority-messages.js

# IIFE Compilation
#all:
#test -d node_modules || npm i
#node build_proto.js
#node build.js
